import Head from "next/head";

const NotFound = () => {
   
    return ( 
        <div className="not-found">
             <Head>
        <title>DashBoard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1>Page Not Found</h1>
        </main>
        </div>
     );
}
 
export default NotFound;