import Head from 'next/head'
import PreFund from '../components/Wallet/PreFund'
import PostFund from '../components/Wallet/PostFund'

const API =()=>{
    return(
        <>
        <Head>
        <title>API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
       
        </main>
        </>
    )
}

export default API