import Head from 'next/head'

// custom components


export default function Home() {
  return (
    <>
      <Head>
        <title>DashBoard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
         
      </main>
    </>
  )
}
