import Head from 'next/head'
import Input from '../components/resuables/Input'
import Button from '../components/resuables/Button'

// custom components


export default function Home() {
  return (
    <>
      <Head>
        <title>DashBoard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
         <Input label="Email" placeholder="Email" state={""} type="email" onChange={()=>{}}/>
          <Button title="Sign In" action={()=>{
            
          }}/>
      </main>
    </>
  )
}
