import Head from 'next/head'
import Analytic from '../components/Dashboard/Analytics'
import Graph from '../components/Dashboard/Graph'
import History from '../components/Dashboard/History'
import Wallet from '../components/Dashboard/Wallet'
import ExchangeRate from '../components/ExchangeRate'

// custom components


export default function Home() {
  return (
    <>
      <Head>
        <title>DashBoard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
         <div className="row">
          <div className="container">
            <Wallet/>
          </div>
          <div className="container">
          <Analytic/>
          <ExchangeRate />
          </div>
         </div>

         <div className="row">
          <div className="container">
            <Graph />
          </div>
          <div className="container">
            <History/>
          </div>
         </div>
      </main>
    </>
  )
}
