import Head from 'next/head'
import { useState } from 'react'
import Router,{ useRouter } from 'next/router'
import logo from '../public/images/fp_logo.png'
import Image from 'next/image'

import Login from '../components/Login/Login'
import Auth2FA from '../components/Login/Auth2fa'
import Confirm2FA from '../components/Login/Confirm2FA'

import style from '../styles/login.module.css'
// custom components
const LoginController=async (username:string,password:string)=>{

    try{

        let login = await fetch("/api/login",{
            method:"POST",
            headers:{
                "Content-Type":"application/json"
            },
            body:JSON.stringify({username,password}) 
        })

        if(!login.ok){
          let errors = await login.json()

          throw errors.message

        }
         
        
       return true
    }
    catch(error){

        throw error

    }

}

// interface HomeProp{
//   loggedIn:boolean
// }

 const Home=()=> {
  const router = useRouter()

    const [userName,setUsername] = useState<string>('')
    const [userPassword,setUserPassword] = useState<string>('')

    const [two_f_a,setTFA]=useState<string>('');

    const [loggedIn,setLoggedIn] = useState<boolean>(false)
    const [scanned,setScanned]=useState<boolean>(false)
    const [verified,setVerified]=useState<boolean>(false)

    const handleLogin= async ()=>{
        let login =await LoginController(userName,userPassword)

        // if(login){
        //   setLoggedIn(true)
        // }
        setLoggedIn(true)
    }
    
    const handleQR =async()=>{
      setScanned(true)
    }


    const handleConfirm = async()=>{

      setVerified(true)
    }


    

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={style.row}>

        <div className={style.container}>
          <div className={style.form_container}>

          {!loggedIn&&<Login btnAction={handleLogin} password={userPassword} passControl={(e)=>setUserPassword(e.target.value)} username={userName} userControl={(e)=>setUsername(e.target.value)} />}

          {loggedIn&&!scanned&&<Auth2FA QRcode="qr_code" action={handleQR} />}

          {scanned?<Confirm2FA state={two_f_a} setState={(e)=>setTFA(e.target.value)} action={handleConfirm} />:null}
       
        <div className={style.footer}>
                  <h5>footer</h5>
        </div>
          </div>
         
        </div>

        <div className={style.container}>
          <div className={style.fp_logo}>

            <div className={style.fp_circle}>

              <div className={style.image}>
                  <Image src={logo} width="350"  layout="intrinsic" />
              </div>
            
            </div>

          </div>

        </div>

       
          
      </div>
    </>
  )
}

export default Home