import Head from "next/head"
import Analytic from "../components/Transaction/Analytic"
const Transaction =()=>{
    return(
        <>
        <Head>
        <title>Transactions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
          <div className="row">
        <Analytic />
          </div>

      </main>
        </>
    )
}

export default Transaction