import Head from 'next/head'
import PreFund from '../components/Wallet/PreFund'
import PostFund from '../components/Wallet/PostFund'

const Wallet =()=>{
    return(
        <>
        <Head>
        <title>Wallet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <div className="row">
            <div className="container">
            <PreFund />
            </div>
            <div className="container">
            <PostFund />
            </div>
        </div>
        </main>
        </>
    )
}

export default Wallet