<template>
  <div class="layout">
    <PageLoader v-if="loading" />
    <!-- Left content -->
    <div class="layout_left_content">
      <div class="layout_left_inner_content">
        <!-- Logo -->
        <div class="layout_logo">
          <img src="@/assets/images/logo.png" alt="Vue logo" />
        </div>
        <!-- End of Logo -->
        <!-- Login Form -->
        <div class="form_container">
          <!-- Title -->
          <h2 class="form_title">Authenticate your account</h2>
          <!-- End of title -->
          <!-- Small text -->
          <p class="welcome-text">
            Enter the code generated by your authenticator app.
          </p>
          <!-- End of Small text -->
          <!-- 2FA Verification Container -->
          <div class="two_factor_auth_container">
            <v-otp-input
              ref="otpInput"
              input-classes="otp-input"
              separator=" "
              :num-inputs="6"
              :should-auto-focus="true"
              :is-input-num="true"
              :conditionalClass="['one', 'two', 'three', 'four']"
              :placeholder="['', '', '', '', '', '']"
              @on-change="handleOnChange"
              @on-complete="handleOnComplete"
            />
          </div>
          <!-- End of 2FA Verification Container -->
        </div>
        <!-- End of Login Form -->
        <!-- <p class="terms">Term of use & Privacy policy</p> -->
      </div>
    </div>
    <!-- Right content -->
    <div class="layout_right_content">
      <div class="layout_right_inner_content">
        <TwoFactorAuthVerifySVG />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import TwoFactorAuthVerifySVG from "../../components/icons/auth/TwoFactorAuthVerifySVG.vue";
import VOtpInput from "vue3-otp-input";
import PageLoader from "@/components/common/PageLoader.vue";
import axios from "axios";
import Swal from "sweetalert2";
import { useStore } from "vuex";
import { useRouter } from "vue-router";
import { ref, computed } from "vue";

// Initialize the store
const store = useStore();

// Initialize the router
const router = useRouter();

// Get loading status
const loading = computed(() => store.getters.getLoadingStatus);

// Get the token
const token = computed(() => store.getters.getToken);

const otpInput = ref(null);

const handleOnComplete = async (value: string) => {
  // Set loading status
  store.dispatch("isLoading");

  // Submit the 2FA code
  await axios
    .post(
      "/2fa/verify",
      {
        code: value,
      },
      {
        headers: {
          Authorization: `Bearer ${token.value}`,
        },
      }
    )
    .then((response) => {
      // Set loading status
      store.dispatch("isLoading");
      if (response.status === 200) {
        console.log("2FA code verified");
        // Redirect to dashboard
        router.push({ name: "dashboard" });
      }
    })
    .catch((error) => {
      // Set loading status
      store.dispatch("isLoading");

      // Show error message
      if (error.response) {
        Swal.fire({
          icon: "error",
          title: "Error",
          text: error.response.data.errors.join(" "),
        });
      }
    });
};

const handleOnChange = (value: string) => {
  console.log("OTP changed: ", value);
};
</script>

<style>
.form_title {
  text-align: center;
  margin-bottom: 1rem;
}

.two_factor_auth_container {
  display: flex;
  align-items: center;
  justify-content: center;
  margin-bottom: 2rem;
  margin-top: 2rem;
}

.otp-input {
  width: 50px;
  height: 50px;
  padding: 5px;
  margin: 0 10px;
  font-size: 20px;
  border-radius: 4px;
  border: 1px solid rgba(0, 0, 0, 0.3);
  text-align: center;
  box-shadow: rgba(50, 50, 93, 0.25) 0px 50px 100px -20px,
    rgba(0, 0, 0, 0.3) 0px 30px 60px -30px;
}
/* Background colour of an input field with value */
.otp-input.is-complete {
  background-color: #fff;
}
.otp-input::-webkit-inner-spin-button,
.otp-input::-webkit-outer-spin-button {
  -webkit-appearance: none;
  margin: 0;
}
</style>
